import { getPriceEdits } from '../stock'

describe('Adjust prices', () => {
  const priceObj = { vendorCut: '10', storeCut: '5', totalSell: '15.00', margin: null }
  it('should correctly adjust when the vendor cut changes', () => {
    const priceEdit = getPriceEdits(priceObj, 'vendorCut', '8')
    expect(priceEdit.vendorCut).toBe('8')
    expect(priceEdit.storeCut).toBe('7.00')
    expect(priceEdit.totalSell).toBe('15.00')
    expect(priceEdit.margin).toBe('46.7')
  })
  it('should correctly adjust when the store cut changes', () => {
    const priceEdit = getPriceEdits(priceObj, 'storeCut', '2')
    expect(priceEdit.vendorCut).toBe('10')
    expect(priceEdit.storeCut).toBe('2')
    expect(priceEdit.totalSell).toBe('12.00')
    expect(priceEdit.margin).toBe('16.7')
  })
  it('should correctly adjust when the total sell changes', () => {
    const priceEdit = getPriceEdits(priceObj, 'totalSell', '17')
    expect(priceEdit.vendorCut).toBe('10')
    expect(priceEdit.storeCut).toBe('7.00')
    expect(priceEdit.totalSell).toBe('17')
    expect(priceEdit.margin).toBe('41.2')
  })
  it('should correctly adjust when the margin changes', () => {
    const priceEdit = getPriceEdits(priceObj, 'margin', '41.2')
    expect(priceEdit.vendorCut).toBe('10')
    expect(priceEdit.storeCut).toBe('7.00')
    expect(priceEdit.totalSell).toBe('17.00')
    expect(priceEdit.margin).toBe('41.2')
  })
  it('should correctly adjust when the vendor cut changes, totalSell Locked', () => {
    const priceEdit = getPriceEdits(priceObj, 'vendorCut', '8', 'totalSell')
    expect(priceEdit.vendorCut).toBe('8')
    expect(priceEdit.storeCut).toBe('7.00')
    expect(priceEdit.totalSell).toBe('15.00')
    expect(priceEdit.margin).toBe('46.7')
  })
  it('should correctly adjust when the store cut changes, totalSell Locked', () => {
    const priceEdit = getPriceEdits(priceObj, 'storeCut', '2', 'totalSell')
    expect(priceEdit.vendorCut).toBe('13.00')
    expect(priceEdit.storeCut).toBe('2')
    expect(priceEdit.totalSell).toBe('15.00')
    expect(priceEdit.margin).toBe('13.3')
  })
  it('should correctly adjust when the total sell changes, totalSell Locked', () => {
    const priceEdit = getPriceEdits(priceObj, 'totalSell', '17', 'totalSell')
    expect(priceEdit.vendorCut).toBe('10')
    expect(priceEdit.storeCut).toBe('7.00')
    expect(priceEdit.totalSell).toBe('17')
    expect(priceEdit.margin).toBe('41.2')
  })
  it('should correctly adjust when the margin changes, totalSell Locked', () => {
    const priceEdit = getPriceEdits(priceObj, 'margin', '41.2', 'totalSell')
    expect(priceEdit.vendorCut).toBe('9.00')
    expect(priceEdit.storeCut).toBe('6.00')
    expect(priceEdit.totalSell).toBe('15.00')
    expect(priceEdit.margin).toBe('41.2')
  })
  it('should correctly adjust when the vendor cut changes, storeCut Locked', () => {
    const priceEdit = getPriceEdits(priceObj, 'vendorCut', '8', 'storeCut')
    expect(priceEdit.vendorCut).toBe('8')
    expect(priceEdit.storeCut).toBe('5')
    expect(priceEdit.totalSell).toBe('13.00')
    expect(priceEdit.margin).toBe('38.5')
  })
  it('should correctly adjust when the store cut changes, storeCut Locked', () => {
    const priceEdit = getPriceEdits(priceObj, 'storeCut', '2', 'storeCut')
    expect(priceEdit.vendorCut).toBe('10')
    expect(priceEdit.storeCut).toBe('2')
    expect(priceEdit.totalSell).toBe('12.00')
    expect(priceEdit.margin).toBe('16.7')
  })
  it('should correctly adjust when the total sell changes, storeCut Locked', () => {
    const priceEdit = getPriceEdits(priceObj, 'totalSell', '17', 'storeCut')
    expect(priceEdit.vendorCut).toBe('12.00')
    expect(priceEdit.storeCut).toBe('5')
    expect(priceEdit.totalSell).toBe('17')
    expect(priceEdit.margin).toBe('29.4')
  })
  it('should correctly adjust when the margin changes, storeCut Locked', () => {
    const priceEdit = getPriceEdits(priceObj, 'margin', '33.3', 'storeCut')
    expect(priceEdit.vendorCut).toBe('10.00')
    expect(priceEdit.storeCut).toBe('5')
    expect(priceEdit.totalSell).toBe('15.00')
    expect(priceEdit.margin).toBe('33.3')
  })
  it('should correctly adjust when the vendor cut changes, margin Locked', () => {
    const priceEdit = getPriceEdits(priceObj, 'vendorCut', '8', 'margin')
    expect(priceEdit.vendorCut).toBe('8')
    expect(priceEdit.storeCut).toBe('4.00')
    expect(priceEdit.totalSell).toBe('12.00')
    expect(priceEdit.margin).toBe('33.3')
  })
  it('should correctly adjust when the store cut changes, margin Locked', () => {
    const priceEdit = getPriceEdits(priceObj, 'storeCut', '2', 'margin')
    expect(priceEdit.vendorCut).toBe('4.00')
    expect(priceEdit.storeCut).toBe('2')
    expect(priceEdit.totalSell).toBe('6.00')
    expect(priceEdit.margin).toBe('33.3')
  })
  it('should correctly adjust when the total sell changes, margin Locked', () => {
    const priceEdit = getPriceEdits(priceObj, 'totalSell', '12', 'margin')
    expect(priceEdit.vendorCut).toBe('8.00')
    expect(priceEdit.storeCut).toBe('4.00')
    expect(priceEdit.totalSell).toBe('12')
    expect(priceEdit.margin).toBe('33.3')
  })
  it('should correctly adjust when the margin changes, margin Locked', () => {
    const priceEdit = getPriceEdits(priceObj, 'margin', '20', 'margin')
    expect(priceEdit.vendorCut).toBe('10')
    expect(priceEdit.storeCut).toBe('3.00')
    expect(priceEdit.totalSell).toBe('13.00')
    expect(priceEdit.margin).toBe('20')
  })
})
