exports.seed = (knex) =>
  knex('sale_item')
    .del()
    .then(() =>
      knex('sale_item').insert([
        {
          id: 1,
          sale_id: 1,
          item_id: 1,
          quantity: 1,
          vendor_discount: null,
          is_refunded: 0,
          is_deleted: 0,
        },
        {
          id: 2,
          sale_id: 2,
          item_id: 4,
          quantity: 1,
          vendor_discount: null,
          is_refunded: 0,
          is_deleted: 1,
        },
        {
          id: 3,
          sale_id: 3,
          item_id: 3,
          quantity: 1,
          vendor_discount: null,
          is_refunded: 0,
          is_deleted: 0,
        },
        {
          id: 4,
          sale_id: 4,
          item_id: 5,
          quantity: 1,
          vendor_discount: null,
          is_refunded: 0,
          is_deleted: 0,
        },
        {
          id: 5,
          sale_id: 5,
          item_id: 7,
          quantity: 1,
          vendor_discount: null,
          is_refunded: 0,
          is_deleted: 0,
        },
        {
          id: 6,
          sale_id: 6,
          item_id: 8,
          quantity: 2,
          vendor_discount: null,
          is_refunded: 0,
          is_deleted: 0,
        },
        {
          id: 7,
          sale_id: 7,
          item_id: 9,
          quantity: 1,
          vendor_discount: 50,
          is_refunded: 0,
          is_deleted: 0,
        },
        {
          id: 8,
          sale_id: 8,
          item_id: 10,
          quantity: 2,
          vendor_discount: 20,
          is_refunded: 0,
          is_deleted: 0,
        },
        {
          id: 9,
          sale_id: 9,
          item_id: 4,
          quantity: 1,
          vendor_discount: null,
          is_refunded: 0,
          is_deleted: 0,
        },
        {
          id: 10,
          sale_id: 7,
          item_id: 6,
          quantity: 1,
          vendor_discount: null,
          is_refunded: 0,
          is_deleted: 0,
        },
        {
          id: 11,
          sale_id: 8,
          item_id: 6,
          quantity: 1,
          vendor_discount: null,
          is_refunded: 0,
          is_deleted: 0,
        },
        {
          id: 12,
          sale_id: 9,
          item_id: 6,
          quantity: 1,
          vendor_discount: null,
          is_refunded: 0,
          is_deleted: 0,
        },
        {
          id: 13,
          sale_id: 7,
          item_id: 7,
          quantity: 5,
          vendor_discount: null,
          is_refunded: 0,
          is_deleted: 0,
        },
        {
          id: 14,
          sale_id: 8,
          item_id: 7,
          quantity: 1,
          vendor_discount: 20,
          is_refunded: 0,
          is_deleted: 0,
        },
        {
          id: 15,
          sale_id: 9,
          item_id: 7,
          quantity: 2,
          vendor_discount: 70,
          is_refunded: 0,
          is_deleted: 0,
        },
        {
          id: 16,
          sale_id: 10,
          item_id: 7,
          quantity: 2,
          vendor_discount: 100,
          is_refunded: 0,
          is_deleted: 0,
        },
        {
          id: 17,
          sale_id: 11,
          item_id: 11,
          quantity: 1,
          vendor_discount: null,
          is_refunded: 0,
          is_deleted: 0,
        },
        {
          id: 18,
          sale_id: 12,
          item_id: 11,
          quantity: 1,
          vendor_discount: null,
          is_refunded: 0,
          is_deleted: 0,
        },
        {
          id: 19,
          sale_id: 13,
          item_id: 11,
          quantity: 1,
          vendor_discount: null,
          is_refunded: 0,
          is_deleted: 0,
        },
      ]),
    )
