export const seed = (knex) =>
  knex('stock')
    .del()
    .then(() =>
      knex('stock').insert([
        {
          id: 1,
          vendor_id: 1,
          artist: 'The Beatles',
          title: 'Abbey Road',
          format: '7"',
          is_deleted: 0,
        },
        {
          id: 2,
          vendor_id: 1,
          artist: 'The Cure',
          title: 'Pornography',
          format: '7"',
          is_deleted: 0,
        },
        {
          id: 3,
          vendor_id: 2,
          artist: 'Weyes Blood',
          title: 'Front Row Seat to Earth',
          format: '7"',
          is_deleted: 1,
        },
        {
          id: 4,
          vendor_id: 2,
          artist: 'Wire',
          title: 'Pink Flag',
          format: '7"',
          is_deleted: 0,
        },
        {
          id: 5,
          vendor_id: 42,
          artist: 'Bee Gees',
          title: 'One Night Only',
          format: '2CD',
          is_deleted: 0,
        },
        {
          id: 6,
          vendor_id: 42,
          artist: 'Cream',
          title: 'Best Of',
          format: 'LP',
          is_deleted: 0,
        },
        {
          id: 7,
          vendor_id: 3,
          artist: 'Teletubbies',
          title: 'Eh Oh',
          format: '2CD',
          is_deleted: 0,
        },
        {
          id: 8,
          vendor_id: 4,
          artist: 'The Hives',
          title: 'Best Of',
          format: '3LP',
          is_deleted: 0,
        },
        {
          id: 9,
          vendor_id: 5,
          artist: 'Ox',
          title: 'OxStock',
          format: '2CD',
          is_deleted: 0,
        },
        {
          id: 10,
          vendor_id: 6,
          artist: 'The Clean',
          title: 'Boodle Boodle EP',
          format: 'EP',
          is_deleted: 0,
        },
        {
          id: 11,
          vendor_id: 6,
          artist: 'Price Changer',
          title: 'Box Set',
          format: 'CD',
          is_deleted: 0,
        },
        {
          id: 12,
          title: 'SaveCart Item',
          is_deleted: 0,
        },
        {
          id: 13,
          title: 'SaveCart Item 2',
          is_deleted: 0,
        },
        {
          id: 14,
          title: 'SaveCart Item 3',
          is_deleted: 0,
        },
      ]),
    )
