export const genreLibrary = [
  {
    type: 'Audio',
    divider: 'ALT ROCK/POST ROCK',
    code: 'ALT',
    description: 'ALT ROCK/POST ROCK',
    examples: 'jesus lizard, Primus, Janes addiction',
    googleBooksCategories: '',
    discogsStyles: 'Alternative Rock',
  },
  {
    type: 'Audio',
    divider: 'NOISE/DRONE',
    code: 'NOI',
    description: 'NOISE/DRONE',
    examples: 'Tony Conrad, Dead c, merzbow',
    googleBooksCategories: '',
    discogsStyles: 'Noise Rock',
  },
  {
    type: 'Audio',
    divider: 'AMBIENT',
    code: 'AMB',
    description: 'AMBIENT',
    examples: 'FELBM,Cocteau Twins, Eno',
    googleBooksCategories: '',
    discogsStyles: 'Ambient, Ethereal',
  },
  {
    type: 'Audio',
    divider: 'ART ROCK/EXPERIMENTAL',
    code: 'EXP',
    description: 'ART ROCK/EXPERIMENTAL',
    examples: 'Eno,Cluster, Neu!, Neu,Can,Faust,Amon Duul II',
    googleBooksCategories: '',
    discogsStyles: 'Art Rock, Experimental, Avantgarde',
  },
  {
    type: 'Audio',
    divider: 'INDIE ROCK',
    code: 'IND',
    description: 'INDIE ROCK',
    examples: 'pavement,apples in stereo, Belle and Sebasitan,Neutral Milk Hotel',
    googleBooksCategories: '',
    discogsStyles: 'Indie Rock',
  },
  {
    type: 'Audio',
    divider: 'JANGLE POP',
    code: 'JNG',
    description: 'JANGLE POP',
    examples: 'Bats,Clean,Smiths',
    googleBooksCategories: '',
    discogsStyles: 'Indie Pop',
  },
  {
    type: 'Audio',
    divider: 'BEDROOM POP/CARDIGAN MUSIC',
    code: 'BED',
    description: 'BEDROOM POP/CARDIGAN MUSIC',
    examples: 'Pickle Darling,Bright Eyes',
    googleBooksCategories: '',
    discogsStyles: 'Indie Pop, Lo-Fi',
  },
  {
    type: 'Audio',
    divider: 'SHOEGAZE/DREAMPOP',
    code: 'DRP',
    description: 'SHOEGAZE/DREAMPOP',
    examples: 'MBV, slowdive, dead can dance',
    googleBooksCategories: '',
    discogsStyles: 'Dream Pop',
  },
  {
    type: 'Audio',
    divider: 'POST PUNK/GOTH',
    code: 'GTH',
    description: 'POST PUNK/GOTH',
    examples: 'Cure,wire,gang of four,Bauhaus',
    googleBooksCategories: '',
    discogsStyles: 'Goth Rock, Post-Punk',
  },
  {
    type: 'Audio',
    divider: 'NEW WAVE/POWER POP',
    code: 'NWV',
    description: 'NEW WAVE/POWER POP',
    examples: 'Elvis costello, the cars , blondie',
    googleBooksCategories: '',
    discogsStyles: 'New Wave',
  },
  {
    type: 'Audio',
    divider: 'SYNTHPOP/SYNTHWAVE',
    code: 'SYN',
    description: 'SYNTHPOP/SYNTHWAVE',
    examples: 'ultravox, Gary Numan, Yazoo',
    googleBooksCategories: '',
    discogsStyles: 'Synth-pop, Dungeon Synth, Synthwave',
  },
  {
    type: 'Audio',
    divider: 'EMO/POST-HARDCORE',
    code: 'EMO',
    description: 'EMO/POST-HARDCORE',
    examples: 'Sunny Day Real Estate',
    googleBooksCategories: '',
    discogsStyles: 'Emo, Post-Hardcore',
  },
  { divider: 'FAKE EMO', code: 'MCR', description: 'FAKE EMO', examples: 'My Chemical Romance', discogsStyles: 'Emo' },
  {
    type: 'Audio',
    divider: 'SURF/TWANG',
    code: 'SUR',
    description: 'SURF/TWANG',
    examples: 'Dick Dale,Link Wray,Phantom Surfers,Shadows,Duane Eddy',
    googleBooksCategories: '',
    discogsStyles: 'Surf',
  },
  {
    type: 'Audio',
    divider: 'GARAGE/TRASH',
    code: 'GAR',
    description: 'GARAGE/TRASH',
    examples: 'Cavemen,Oblivians,Gories,BBQ',
    googleBooksCategories: '',
    discogsStyles: 'Garage Rock',
  },
  {
    type: 'Audio',
    divider: 'LOUNGE/MOOG/SPACEAGE',
    code: 'LOU',
    description: 'LOUNGE/MOOG/SPACEAGE',
    examples: 'Martin Denny',
    googleBooksCategories: '',
    discogsStyles: '',
  },
  {
    type: 'Audio',
    divider: 'ROCK AND ROLL/ROCKABILLY',
    code: 'RNR',
    description: 'ROCK AND ROLL/ROCKABILLY/PSYCHOBILLY',
    examples: 'Elvis, Sun Records, Stray Cats, Cramps',
    googleBooksCategories: '',
    discogsStyles: 'Rockabilly, Psychobilly',
  },
  {
    type: 'Audio',
    divider: 'BEAT BOOM',
    code: 'BEA',
    description: 'BEAT BOOM',
    examples: 'Beatles,Troggs,Stones,Sonics',
    googleBooksCategories: '',
    discogsStyles: 'Beat, Mod',
  },
  {
    type: 'Audio',
    divider: 'GIRL GROUPS/DOO-WOP',
    code: 'DOO',
    description: 'GIRL GROUPS/DOO-WOP',
    examples: 'Shangrilas, Platters, Frankie Lymon',
    googleBooksCategories: '',
    discogsStyles: 'Doo Wop',
  },
  {
    type: 'Audio',
    divider: 'BRITPOP',
    code: 'BRT',
    description: 'BRITPOP',
    examples: 'Blur Kinks Pulp Jam Who',
    googleBooksCategories: '',
    discogsStyles: 'Mod, Beat, Brit Pop',
  },
  {
    type: 'Audio',
    divider: 'PSYCH/PROG ROCK',
    code: 'PSY',
    description: 'PSYCH ROCK',
    examples: 'King Gizz, Glass Family',
    googleBooksCategories: '',
    discogsStyles: 'Acid Rock, Psychedelic Rock, Prog Rock, Space Rock',
  },
  { divider: 'POP', code: 'POP', description: 'POP', examples: 'Wham, Beach Boys', discogsStyles: 'Pop' },
  {
    type: 'Audio',
    divider: 'COCAINE ROCK',
    code: 'FBI',
    description: 'COCAINE ROCK',
    examples: 'Ealges,steely Dan,fleetwood mac',
    googleBooksCategories: '',
    discogsStyles: 'Pop Rock, Southern Rock, Country Rock',
  },
  {
    type: 'Audio',
    divider: 'DAD/MUM ROCK (WHEN MUSIC WAS GOOD)',
    code: 'DAD',
    description: 'DAD/MUM ROCK (WHEN MUSIC WAS GOOD)',
    examples: 'CCR,The Faces, Dire Straits,the boss',
    googleBooksCategories: '',
    discogsStyles: 'Pop Rock, Southern Rock, Country Rock',
  },
  {
    type: 'Audio',
    divider: 'INDUSTRIAL',
    code: 'IDS',
    description: 'INDUSTRIAL',
    examples: 'Throbbing Gristle,Coil,Einsturzende Neubauten,SPK',
    googleBooksCategories: '',
    discogsStyles: 'Industrial',
  },
  {
    type: 'Audio',
    divider: 'WEIRD/APOCALPYTIC FOLK',
    code: 'WFK',
    description: 'STRANGE FOLK',
    examples: 'CURRENT 93,Comus,Wicker man,Momus',
    googleBooksCategories: '',
    discogsStyles: 'Folk Rock, Prog Rock',
  },
  {
    type: 'Audio',
    divider: 'RNB/DOO-WOP',
    code: 'RNB',
    description: `R'n'B/SOUL (50s-60s)`,
    examples: 'James brown,Sam cook, Ray Charles',
    googleBooksCategories: '',
    discogsStyles:
      'Bubblegum, Contemporary R&B, Gospel, New Jack Swing, Neo Soul, Rhythm & Blues, Soul, Swingbeat, UK Street Soul',
  },
  {
    type: 'Audio',
    divider: 'SOUL/FUNK/DISCO',
    code: 'SFD',
    description: 'SOUL/FUNK/DISCO/AFROBEAT (70s-Present)',
    examples: 'WAR,rick james,Parliament,Olympians,El Michels Affair, Stevie Wonder, Prince, Fela Kuti',
    googleBooksCategories: '',
    discogsStyles: 'Bayou Funk, Boogie, Free Funk, Funk, Gogo, Minneapolis Sound, P.Funk',
  },
  {
    type: 'Audio',
    divider: 'HIP-HOP',
    code: 'BAP',
    description: 'OLD SCHOOL/BOOM BAP',
    examples: 'Grandmaster Flash, Run DMC',
    googleBooksCategories: '',
    discogsStyles: 'Boom Bap',
  },
  {
    type: 'Audio',
    divider: 'HIP-HOP',
    code: 'HIP',
    description: '90s/2000s HIP-HOP',
    examples: 'Dre, NWA',
    googleBooksCategories: '',
    discogsStyles: 'Bounce, G-Funk, Gangsta, Hardcore Hip-Hop, Miami Bass, Thug Rap',
  },
  {
    type: 'Audio',
    divider: 'HIP-HOP',
    code: 'DRT',
    description: 'MEMPHIS/DIRTY SOUTH',
    examples: 'Outkast,Three Six Mafia,DJ Screw',
    googleBooksCategories: '',
    discogsStyles: 'Gangsta, Crunk, Screw',
  },
  {
    type: 'Audio',
    divider: 'HIP-HOP',
    code: 'XAN',
    description: 'TRAP/SOUNDCLOUD/SADBOI',
    examples: 'Lil Peep,Yung Lean,XXXtentacion',
    googleBooksCategories: '',
    discogsStyles: 'Cloud Rap',
  },
  {
    type: 'Audio',
    divider: 'HIP-HOP',
    code: 'TRP',
    description: 'DOWNBEAT/TRIPHOP',
    examples: 'Portishead, Luscious Jackson, DJ Shadow',
    googleBooksCategories: '',
    discogsStyles: 'Trip Hop, Downbeat',
  },
  {
    type: 'Audio',
    divider: 'HIP-HOP',
    code: 'UGD',
    description: 'CONSCIOUS/UNDERGROUND/EXPERIMENTAL',
    examples: 'Immortal Technique, Mos Def, Flying Lotus, Deltron 3030,Kendrick',
    googleBooksCategories: '',
    discogsStyles: 'Conscious, Horrorcore, Jazzy Hip-Hop, Turntablism',
  },
  {
    type: 'Audio',
    divider: 'COUNTRY ',
    code: 'COU',
    description: 'CLASSIC COUNTRY/GOSPEL',
    examples: 'Hank, Johnny etc',
    googleBooksCategories: '',
    discogsStyles: '',
  },
  {
    type: 'Audio',
    divider: 'COUNTRY ',
    code: 'LYT',
    description: 'MODERN/ALT COUNTRY',
    examples: 'Palace Bros, Marlon',
    googleBooksCategories: '',
    discogsStyles: '',
  },
  {
    type: 'Audio',
    divider: 'COUNTRY ',
    code: 'AME',
    description: 'AMERICANA',
    examples: 'Gram Parsons , Guy Clark',
    googleBooksCategories: '',
    discogsStyles: '',
  },
  { divider: 'JAZZ', code: 'SHT', description: 'JAZZ FUSION', examples: '', discogsStyles: '' },
  { divider: 'JAZZ', code: 'MOD', description: 'MODERN JAZZ', examples: '', discogsStyles: '' },
  { divider: 'JAZZ', code: 'PRE', description: 'PRE-WAR JAZZ', examples: 'Charlie Parker, Dizzie ', discogsStyles: '' },
  {
    type: 'Audio',
    divider: 'JAZZ',
    code: 'JAZ',
    description: 'POST WAR JAZZ',
    examples: 'Kamasi Washington, Miles Davis',
    googleBooksCategories: '',
    discogsStyles: '',
  },
  { divider: 'FOLK/BLUES', code: 'FOK', description: 'FOLK', examples: 'Margo Guryan', discogsStyles: '' },
  {
    type: 'Audio',
    divider: 'FOLK/BLUES',
    code: 'BLU',
    description: 'BLUES',
    examples: '',
    googleBooksCategories: '',
    discogsStyles:
      'Boogie Woogie, Chicago Blues, Country Blues, Delta Blues, East Coast Blues, Electric Blues, Harmonica Blues, Hill Country Blues, Jump Blues, Louisiana Blues, Memphis Blues, Modern Electric Blues, Piano Blues, Piedmont Blues, Texas Blues',
  },
  {
    type: 'Audio',
    divider: 'FOLK/BLUES',
    code: 'LYT',
    description: 'ITS A WORKING PORT',
    examples:
      'Delaney and the Eastern and Billy Bragg and Springsteen like rootin tootin union boostin struggle tunes?',
    googleBooksCategories: '',
    discogsStyles: '',
  },
  {
    type: 'Audio',
    divider: 'REGGAE/DUB/SKA',
    code: 'REG',
    description: 'ROOTS/REGGAE',
    examples: '',
    googleBooksCategories: '',
    discogsStyles: 'Lovers Rock, Reggae, Reggae Gospel, Reggae-Pop, Rocksteady, Roots Reggae',
  },
  { divider: 'REGGAE/DUB/SKA', code: 'DAN', description: 'DANCEHALL', examples: '', discogsStyles: 'Dancehall, Ragga' },
  { divider: 'REGGAE/DUB/SKA', code: 'DUB', description: 'DUB', examples: '', discogsStyles: 'Dub' },
  { divider: 'REGGAE/DUB/SKA', code: 'SKA', description: 'SKA', examples: '', discogsStyles: 'Ska' },
  {
    type: 'Audio',
    divider: 'SPOKEN WORD',
    code: 'SPO',
    description: 'SPOKEN WORD',
    examples: '',
    googleBooksCategories: '',
    discogsStyles: 'Educational, Nursery Rhymes, Story ',
  },
  {
    type: 'Audio',
    divider: 'SOUNDTRACKS',
    code: 'STR',
    description: 'SOUNDTRACKS',
    examples: '',
    googleBooksCategories: '',
    discogsStyles: 'Stage & Screen, Cabaret, Musical, Score, Soundtrack, Theme, Vaudeville, Video Game Music',
  },
  { divider: 'NU METAL', code: 'NU', description: 'NU METAL', examples: 'Bizkit,Korn,Rage', discogsStyles: 'Nu Metal' },
  {
    type: 'Audio',
    divider: 'THRASH/SPEED METAL/CROSSOVER',
    code: 'SPD',
    description: 'THRASH/SPEED METAL/CROSSOVER',
    examples: 'Anthrax, SOD , megadeath, metallica',
    googleBooksCategories: '',
    discogsStyles: 'Speed Metal, Thrash',
  },
  {
    type: 'Audio',
    divider: 'CLASSIC METAL',
    code: 'CLM',
    description: 'CLASSIC METAL',
    examples: 'Iron maiden, dio , judas priest',
    googleBooksCategories: '',
    discogsStyles: 'Heavy Metal',
  },
  { divider: 'DEATH METAL', code: 'DTH', description: 'DEATH METAL', examples: '', discogsStyles: 'Death Metal' },
  {
    type: 'Audio',
    divider: 'SLUDGE/STONER/DESERT',
    code: 'THC',
    description: 'SLUDGE/STONER/DESERT',
    examples: 'electric wizard,earth,high on fire',
    googleBooksCategories: '',
    discogsStyles: 'Sludge Metal',
  },
  {
    type: 'Audio',
    divider: 'BLACK METAL',
    code: 'BLK',
    description: 'BLACK METAL',
    examples: 'Darkthrone, Burzum',
    googleBooksCategories: '',
    discogsStyles: 'Black Metal',
  },
  {
    type: 'Audio',
    divider: 'AMBIENT/DRONE METAL',
    code: 'DNM',
    description: 'AMBIENT/DRONE METAL',
    examples: '',
    googleBooksCategories: '',
    discogsStyles: 'Atmospheric Black Metal',
  },
  {
    type: 'Audio',
    divider: 'FUNERAL/ DOOM CULT',
    code: 'CLT',
    description: 'FUNERAL/ DOOM CULT',
    examples: '',
    googleBooksCategories: '',
    discogsStyles: 'Funeral Doom Metal, Doom Metal',
  },
  {
    type: 'Audio',
    divider: 'ELECTROPUNK/SYNTHPUNK',
    code: 'EPK',
    description: 'ELECTROPUNK/SYNTHPUNK',
    examples: 'Digital Leather,Regurgitator',
    googleBooksCategories: '',
    discogsStyles: 'Punk, Electro',
  },
  {
    type: 'Audio',
    divider: 'GRIND/CRUST/ANARCHO',
    code: 'GRN',
    description: 'GRIND/CRUST/ANARCHO',
    examples: 'Crass,',
    googleBooksCategories: '',
    discogsStyles: 'Punk, Crust, Grindcore',
  },
  {
    type: 'Audio',
    divider: 'STREET PUNK/OI ',
    code: 'OI',
    description: 'STREET PUNK/OI ',
    examples: 'GBH,Exploited,Cockney rejects',
    googleBooksCategories: '',
    discogsStyles: 'Oi',
  },
  {
    type: 'Audio',
    divider: 'HARDCORE/POWERVIOLENCE',
    code: 'HRD',
    description: 'HARDCORE /POWERVIOLENCE',
    examples: '-minor threat, bad brains',
    googleBooksCategories: '',
    discogsStyles: 'Punk, Hardcore, Power Violence',
  },
  {
    type: 'Audio',
    divider: 'FIRST WAVE PUNK',
    code: 'PUN',
    description: 'FIRST WAVE PUNK',
    examples: `Ramones,sex pistols,new york dolls, Buzzcocks  (70'S TIL EARLY 80'S )`,
    googleBooksCategories: '',
    discogsStyles: 'Punk',
  },
  {
    type: 'Audio',
    divider: 'CHOP BONG PUNK',
    code: 'CHP',
    description: 'CHOP BONG PUNK',
    examples: 'NOFX,Chats',
    googleBooksCategories: '',
    discogsStyles: 'Punk, Pop Punk',
  },
  {
    type: 'Audio',
    divider: 'SKA PUNK',
    code: 'SKP',
    description: 'SKA PUNK',
    examples: 'Operation Ivy,Voodoo Glow Skulls',
    googleBooksCategories: '',
    discogsStyles: 'Ska, Punk',
  },
  {
    type: 'Audio',
    divider: 'JUNGLE/DNB',
    code: 'JUN',
    description: 'JUNGLE',
    examples: '',
    googleBooksCategories: '',
    discogsStyles: 'Jungle, Breakbeat, Breakcore',
  },
  {
    type: 'Audio',
    divider: 'JUNGLE/DNB',
    code: 'DNB',
    description: 'DRUMNBASS',
    examples: '',
    googleBooksCategories: '',
    discogsStyles: 'Drum n Bass, Halftime, Jumpstyle, Techstep',
  },
  {
    type: 'Audio',
    divider: 'ELECTRO/ACID',
    code: 'ACD',
    description: 'ELECTRO/ACID',
    examples: 'LEGOWELT,DREXCIYA,EKMEN',
    googleBooksCategories: '',
    discogsStyles: 'Acid, Electro, Electroacoustic, Electroclash',
  },
  {
    type: 'Audio',
    divider: 'HOUSE/TECHNO',
    code: 'HOU',
    description: 'HOUSE',
    examples: '',
    googleBooksCategories: '',
    discogsStyles:
      'Acid House, Baltimore Club, Berlin-School, Deep House, Electro House, Electro Swing, Euro House, Garage House, Ghetto House, Hard House, Hip-House, House, Progressive House, Tech House, Tribal House, Tropical House, UK Funky',
  },
  {
    type: 'Audio',
    divider: 'HOUSE/TECHNO',
    code: 'TEC',
    description: 'TECHNO',
    examples: '',
    googleBooksCategories: '',
    discogsStyles: 'Deep Techno, Dub Techno, Happy Hardcore, Hard Beat, Hard Techno, Minimal Techno, Techno',
  },
  {
    type: 'Audio',
    divider: 'GRIME/DUBSTEP/GARAGE',
    code: 'DBS',
    description: 'DUBSTEP',
    examples: '',
    googleBooksCategories: '',
    discogsStyles: 'Dubstep, Glitch, Glitch Hop',
  },
  {
    type: 'Audio',
    divider: 'GRIME/DUBSTEP/GARAGE',
    code: 'GRI',
    description: 'GRIME/DRILL',
    examples: 'Skepta, Dizzee, Wiley',
    googleBooksCategories: '',
    discogsStyles: 'Grime, Drill',
  },
  { divider: 'GRIME/DUBSTEP/GARAGE', code: 'GRG', description: 'GARAGE', examples: '', discogsStyles: '' },
  { divider: 'DANCE', code: 'DAN', description: 'MISC DANCE/ELECTRONICA', examples: '', discogsStyles: '' },
  { divider: 'DANCE', code: 'BBT', description: 'BIG BEAT/POP DANCE/EURODANCE', examples: '', discogsStyles: '' },
  {
    type: 'Audio',
    divider: 'CLASSICAL',
    code: 'CLA',
    description: '',
    examples: '',
    googleBooksCategories: '',
    discogsStyles:
      'Baroque, Choral, Classical, Contemporary, Early, Impressionist, Medieval, Modern, Neo-Classical, Neo-Romantic, Opera, Operetta, Oratorio, Post-Modern, Renaissance, Romantic, Serial, Twelve-tone, Zarzuela',
  },
  {
    type: 'Literature',
    divider: '',
    code: 'SAD',
    description: 'INDIE SADBOY',
    examples: '',
    discogsStyles: '',
    googleBooksCategories: '',
  },
  {
    type: 'Literature',
    divider: '',
    code: 'ABS',
    description: 'PSYCHEDELIC/ABSTRACT',
    examples: '',
    discogsStyles: '',
    googleBooksCategories: '',
  },
  {
    type: 'Literature',
    divider: '',
    code: 'GAL',
    description: 'BADASS BABES',
    examples: '',
    discogsStyles: '',
    googleBooksCategories: '',
  },
  {
    type: 'Literature',
    divider: '',
    code: 'TOX',
    description: 'TOXIC DUDES',
    examples: '',
    discogsStyles: '',
    googleBooksCategories: '',
  },
  {
    type: 'Literature',
    divider: '',
    code: 'HAH',
    description: 'FUNNY',
    examples: '',
    discogsStyles: '',
    googleBooksCategories: '',
  },
  {
    type: 'Literature',
    divider: '',
    code: 'BOO',
    description: 'SPOOKY',
    examples: '',
    discogsStyles: '',
    googleBooksCategories: '',
  },
  {
    type: 'Literature',
    divider: '',
    code: 'NZ',
    description: 'NEW ZEALAND',
    examples: '',
    discogsStyles: '',
    googleBooksCategories: '',
  },
  {
    type: 'Literature',
    divider: '',
    code: 'BAT',
    description: 'SUPERHEROES',
    examples: '',
    discogsStyles: '',
    googleBooksCategories: '',
  },
  {
    type: 'Literature',
    divider: '',
    code: 'BAD',
    description: 'CRIMINALS',
    examples: '',
    discogsStyles: '',
    googleBooksCategories: '',
  },
  {
    type: 'Literature',
    divider: '',
    code: 'SCI',
    description: 'SCI-FI + FANTASY',
    examples: '',
    discogsStyles: '',
    googleBooksCategories: '',
  },
  {
    type: 'Literature',
    divider: '',
    code: 'DIY',
    description: 'INSTRUCTIONAL/D.I.Y.',
    examples: '',
    discogsStyles: '',
    googleBooksCategories: '',
  },
  {
    type: 'Literature',
    divider: '',
    code: 'TRU',
    description: 'BIO + AUTOBIO',
    examples: '',
    discogsStyles: '',
    googleBooksCategories: '',
  },
  {
    type: 'Literature',
    divider: '',
    code: 'ROK',
    description: 'MUSIC',
    examples: '',
    discogsStyles: '',
    googleBooksCategories: '',
  },
  {
    type: 'Literature',
    divider: '',
    code: 'TRU',
    description: 'TRUE STORIES/EDUCATIONAL',
    examples: '',
    discogsStyles: '',
    googleBooksCategories: '',
  },
  {
    type: 'Literature',
    divider: '',
    code: 'WEI',
    description: 'WEIRD SHIT',
    examples: '',
    discogsStyles: '',
    googleBooksCategories: '',
  },
  {
    type: 'Literature',
    divider: '',
    code: 'ART',
    description: 'PHOTOS + DRAWINGS',
    examples: '',
    discogsStyles: '',
    googleBooksCategories: '',
  },
  {
    type: 'Literature',
    divider: '',
    code: 'GRR',
    description: 'RANTS + RAVES / DEEPLY PERSONAL',
    examples: '',
    discogsStyles: '',
    googleBooksCategories: '',
  },
  {
    type: 'Literature',
    divider: '',
    code: 'SER',
    description: 'SERIOUS SHIT',
    examples: '',
    discogsStyles: '',
    googleBooksCategories: '',
  },
  {
    type: 'Literature',
    divider: '',
    code: 'RHY',
    description: 'WORDS + RHYMES',
    examples: '',
    discogsStyles: '',
    googleBooksCategories: '',
  },
  {
    type: 'Literature',
    divider: '',
    code: 'FAN',
    description: 'FANZINES',
    examples: '',
    discogsStyles: '',
    googleBooksCategories: '',
  },
  {
    type: 'Literature',
    divider: '',
    code: 'WRL',
    description: 'TRAVEL',
    examples: '',
    discogsStyles: '',
    googleBooksCategories: '',
  },
]
