export async function up(knex): Promise<any> {
  return knex.schema.createTable('stock', function (table) {
    table.increments('id').notNullable()
    table.integer('vendor_id', 11).nullable()
    table.string('artist', 256).nullable()
    table.string('title', 256).nullable()
    table.integer('is_deleted', 1).notNullable().defaultTo('0')
    table.string('display_as', 256).nullable()
    table.string('media', 64).nullable()
    table.string('format', 64).nullable()
    table.string('section', 64).nullable()
    table.text('genre')
    table.integer('is_new', 1).notNullable().defaultTo('0')
    table.string('cond', 64).nullable()
    table.string('country', 64).nullable()
    table.string('release_year', 11).nullable()
    table.string('barcode', 128).nullable()
    table.string('publisher', 128).nullable()
    table.string('colour', 64).nullable()
    table.string('size', 64).nullable()
    table.integer('image_id', 11).nullable()
    table.string('image_url', 256).nullable()
    table.string('thumb_url', 256).nullable()
    table.integer('google_books_item_id', 11).nullable()
    table.integer('discogs_item_id', 11).nullable()
    table.integer('do_list_on_website', 1).notNullable().defaultTo('1')
    table.integer('has_no_quantity', 1).notNullable().defaultTo('0')
    table.integer('is_gift_card', 1).defaultTo('0')
    table.string('gift_card_code', 16).nullable()
    table.integer('gift_card_amount', 11).nullable()
    table.integer('gift_card_remaining', 11).nullable()
    table.integer('gift_card_is_valid', 1).nullable()
    table.integer('is_misc_item', 1).defaultTo('0')
    table.string('misc_item_description', 256).nullable()
    table.integer('misc_item_amount', 11).nullable()
    table.integer('created_by_id', 11).nullable()
    table.time('date_created').notNullable().defaultTo(knex.fn.now())
    table.time('date_last_stocktake').nullable()
    table.time('date_modified').notNullable().defaultTo(knex.fn.now())
    table.integer('needs_restock', 1).defaultTo('0')
    table.text('tags')
  })
}

export async function down(knex): Promise<any> {
  return knex.schema.dropTable('stock')
}
