name: Build & Deploy

on:
  push:
    branches: [ross2.0]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ROSS - Digital Ocean
    steps:
      - name: Deploy Ride On Super Sound
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          password: ${{secrets.SSH_PASSWORD}}

          script: |
            cd rideonsupersound
            git pull origin ross2.0
            npm install --legacy-peer-deps &&
            npm run build &&
            pm2 restart rideonsupersound
